### PR TITLE
Insert an image from the guaranteed array during each karaoke session.

### PR DESCRIPTION
**Pull request by fonglh**
Add a couple of bozz pictures to demonstrate.

Enhance Supersized to put guaranteed images at the back and track where they start.

Schedule a guaranteed image to appear when starting a karaoke session.

### CODE REVIEW

**Comment by fonglh** [comment]
@eleybourn This is embarrassing but I just noticed I opened this PR on your repository instead of onto my own fork.

I'm quite happy to contribute the feature but would rather not use those images. I'll do another PR to replace them in a bit. Sorry for the trouble.

**Comment by eleybourn** [comment]
No worries. Just send a PR and I'll change it straight away.

**Comment by eleybourn** [comment]
Actually. I'm about to commit another merge. So I'll delete the images myself.

**Comment by fonglh** [comment]
Thank you!

**Pull request merged**
